sudo: false
dist: trusty
language: cpp

notifications:
  email:
    recipients:
      - 0f9234u9f0jw3@gmx.de
    on_success: always
    on_failure: always

addons:
  apt:
    update: true
    sources: &apt_sources
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty
      - llvm-toolchain-trusty-4.0
      - llvm-toolchain-trusty-5.0
      - llvm-toolchain-trusty-6.0
    packages:
      ["ruby-full", "python3", "python3-pip"]

compiler: clang
os: linux

matrix:
  include:
    # GCC 7
    - env: COMPILER=g++-7
      compiler: gcc
      addons: &gcc7
        apt:
          packages: ["g++-7",     "g++-7-multilib",   "libc6-dbg", "libc6-dbg:i386", "linux-libc-dev", "linux-libc-dev:i386"]
          sources: *apt_sources

    # GCC 8
    - env: COMPILER=g++-8
      compiler: gcc
      addons: &gcc8
        apt:
          packages: ["g++-8",     "g++-8-multilib",   "libc6-dbg", "libc6-dbg:i386", "linux-libc-dev", "linux-libc-dev:i386"]
          sources: *apt_sources

    # GCC 9
    - env: COMPILER=g++-9
      compiler: gcc
      addons: &gcc9
        apt:
          packages: ["g++-9",     "g++-9-multilib",   "libc6-dbg", "libc6-dbg:i386", "linux-libc-dev", "linux-libc-dev:i386"]
          sources: *apt_sources
          
    # Clang 4.0
    - env: COMPILER=clang++-4.0
      addons: &clang40
        apt:
          packages: ["clang-4.0", "g++-6-multilib", "libc6-dbg", "libc6-dbg:i386", "linux-libc-dev", "linux-libc-dev:i386", "g++-6"]
          sources: *apt_sources

    # Clang 5.0
    - env: COMPILER=clang++-5.0
      addons: &clang50
        apt:
          packages: ["clang-5.0", "g++-6-multilib", "libc6-dbg", "libc6-dbg:i386", "linux-libc-dev", "linux-libc-dev:i386", "g++-6"]
          sources: *apt_sources

before_install:
  - pyenv shell 3.6.3
  - pip3 install numpy
  - pip3 install matplotlib
  - pip3 install pandas

install:
  - wget --no-check-certificate --quiet https://github.com/Kitware/CMake/releases/download/v3.18.0-rc4/cmake-3.18.0-rc4-Linux-x86_64.tar.gz
  - tar xzf cmake-3.18.0-rc4-Linux-x86_64.tar.gz
  - mv cmake-3.18.0-rc4-Linux-x86_64 cmake
  - export PATH=${DEPS_DIR}/cmake/bin:${PATH}

script:
  - /usr/bin/$(printenv COMPILER) --version
  # Debug
  - echo "Debug"
  - ./build.sh --build_type=Debug
  - ./test.sh --build_type=Debug
  - ./fix_csvs.sh --build_type=Debug
  - ./generate_images.sh
  - ./clean.sh
  - printf "\n\n"
  # Release
  - echo "Release"
  - ./build.sh --build_type=Release
  - ./test.sh --build_type=Release
  - ./fix_csvs.sh --build_type=Release
  - ./generate_images.sh

