matrix:
  fast_finish: false
  
environment:
  matrix:
    - gen: "MinGW"
    - gen: "MSVC"

clone_script:
  - cmd: >-
      git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
      && cd %APPVEYOR_BUILD_FOLDER%
      && git checkout -qf %APPVEYOR_REPO_COMMIT%
      && git submodule update --init --recursive

install:
  - pip install numpy --user
  - python -m pip install -U matplotlib --user
  - pip install pandas --user

build_script:
  - echo "Debug"
  - build.bat --build_type=Debug --compiler=%gen%
  - test.bat --build_type=Debug
  - fix_csvs.bat --build_type=Debug --compiler=%gen%
  - generate_images.bat
  - echo "Release"
  - build.bat --build_type=Release --compiler=%gen%
  - test.bat --build_type=Release
  - fix_csvs.bat --build_type=Release --compiler=%gen%
  - generate_images.bat

