matrix:
  fast_finish: false
  
environment:
  matrix:
    - gen: "MinGW"
    - gen: "MSVC"

clone_script:
  - cmd: >-
      git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
      && cd %APPVEYOR_BUILD_FOLDER%
      && git checkout -qf %APPVEYOR_REPO_COMMIT%
      && git submodule update --init --recursive

install:
  - cmd: C:\Python34\Scripts\pip.exe install numpy
  - cmd: C:\Python34\Scripts\pip.exe install matplotlib
  - cmd: C:\Python34\Scripts\pip.exe install pandas

before_build:
  - cmd: set PATH=%PATH:C:\Program Files\Git\usr\bin;=% 

build_script:
  - cmd: echo "Debug"
  - cmd: build.bat --build_type=Debug --compiler=%gen%
  - cmd: test.bat --build_type=Debug
  - cmd: fix_csvs.bat --build_type=Debug --compiler=%gen%
  - cmd: generate_images.bat
  - cmd: echo "Release"
  - cmd: build.bat --build_type=Release --compiler=%gen%
  - cmd: test.bat --build_type=Release
  - cmd: fix_csvs.bat --build_type=Release --compiler=%gen%
  - cmd: generate_images.bat

