image: Visual Studio 2019

matrix:
  fast_finish: false

environment:
  matrix:
    - gen: "MinGW"
    - gen: "MSVC"

clone_script:
  - cmd: >-
      git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
      && cd %APPVEYOR_BUILD_FOLDER%
      && git checkout -qf %APPVEYOR_REPO_COMMIT%
      && git submodule update --init --recursive

install:
  - cmd: C:\Python38-x64\Scripts\pip.exe install numpy scipy matplotlib ipython jupyter pandas sympy nose

before_build:
  - cmd: set PATH=%PATH:C:\Program Files\Git\usr\bin;=% # Remove Git sh.exe from PATH so that CMake will generate MinGW Makefiles.
  - cmd: set PATH=C:\Python38-x64;%PATH%

build_script:
  - cmd: echo "Debug"
  - cmd: build.bat --build_type=Debug --compiler=%gen%
  - cmd: test.bat --build_type=Debug
  - cmd: fix_csvs.bat --build_type=Debug --compiler=%gen%
  - cmd: generate_images.bat
  - cmd: count.bat --build_type=Debug --compiler=%gen%
  - cmd: filter.bat --filter_sample_count=125
  - cmd: segment.bat --csv_file_path=resources/Mike/2020-07-02_14.38.40_out_avg_filter_125.csv --sensor=770 --imu=accelerometer --segmentation_kind=both --window_size=51
  - cmd: echo "Release"
  - cmd: build.bat --build_type=Release --compiler=%gen%
  - cmd: test.bat --build_type=Release
  - cmd: fix_csvs.bat --build_type=Release --compiler=%gen%
  - cmd: generate_images.bat
  - cmd: count.bat --build_type=Release --compiler=%gen%
  - cmd: filter.bat --filter_sample_count=125
  - cmd: segment.bat --csv_file_path=resources/Mike/2020-07-02_14.38.40_out_avg_filter_125.csv --sensor=770 --imu=accelerometer --segmentation_kind=both --window_size=51
  - cmd: compare_segmentation.bat --build_type=Release --compiler=%gen%

